# Generated by Django 3.1.7 on 2021-04-28 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210427_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frm', models.CharField(max_length=145)),
                ('to', models.CharField(max_length=145)),
                ('msg', models.CharField(max_length=1405)),
            ],
        ),
    ]
