# Generated by Django 3.1.7 on 2021-04-28 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('a', 'Male'), ('b', 'Female')], default='male', max_length=6),
        ),
    ]
