# Generated by Django 3.1.7 on 2021-04-28 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210428_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.IntegerField(choices=[('1', 'Male'), ('0', 'Female')], default='1', max_length=1),
        ),
    ]
