# Generated by Django 3.1.7 on 2021-04-29 07:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210428_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='delivered',
            field=models.IntegerField(choices=[(1, 'Delivered'), (0, 'Not Delivered')], default=0),
        ),
    ]
