# Generated by Django 3.1.7 on 2021-04-29 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20210429_1310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='date',
            new_name='date_created',
        ),
    ]
